config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "todos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :todos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
    @todos = current_user.todos
  end

  def show
    @todo = current_user.todos.find(params[:id])

  end

  def new
    @todo = current_user.todos.new
  end

  def create

    new_todo = current_user.todos.create(todo_params)
    new_todo.save

    redirect_to new_todo

  end

  def edit
    @todo = current_user.todos.find(params[:id])
  end

  def update

    todo = current_user.todos.find(params[:id])
    todo.update(todo_params)

    redirect_to todo
  end

  def destroy
    current_user.todos.destroy(params[:id])
    redirect_to todos_url
  end

  protected
  def todo_params
    params.require(:todo).permit(:title, :item)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<p class="navbar-text pull-right">

  		<% if user_signed_in? %>

		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

  		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>


  		<% end %>
  	</p>

  	<% if notice %>
  		<p class="alert alert-success"> <%= notice %> </p>
  	<% end %>

  	<% if alert %>
  		<p class="alert alert-danger"> <%= alert %> </p>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>

  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :item %>
  <br>
  <%= f.text_area :item %>

  <%= f.submit %>


<% end %>

app/views/todos/_todo.html.erb
<div class="border">
	<p><strong><%= todo.title %></strong></p>
	<p><%= todo.item %></p>
  	<%= link_to "Show Page", todo if action_name == "index" %> |
  	<%= link_to "Edit Page", edit_todo_path(todo) %>
</div>

<br>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render "form" %>

app/views/todos/index.html.erb
<h1 class="pull-left">Todos</h1>

<%= link_to "New Todo", new_todo_path %>
<br>
<%= render @todos %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Todo Show Page</h1>

<a href="/todos"><button>HOME PAGE</button><br></a>


  <%= render @todo %>

<%= link_to "Delete", @todo, method: :delete, data: { confirm: "Are you sure?" } %>